### ISSUE TITLE
Found some issues in 'train_all_multitask.py'

### ISSUE THREAD

**Issue by liveseongho** [VALUE-Leaderboard/StarterCode#10]
Hi @linjieli222 

I found some issues while I try [train_all_multitask.py](https://github.com/VALUE-Leaderboard/StarterCode/blob/7f124b4ddef86af887ca593b369d470bb0e3586b/train_all_multitask.py).

https://github.com/VALUE-Leaderboard/StarterCode/blob/7f124b4ddef86af887ca593b369d470bb0e3586b/train_all_multitask.py#L52-L53

I think `train_vcmr` and `train_vr` should be modified to `train_retrieval` according to the current StarterCode. Current [train_all_multitask.py](https://github.com/VALUE-Leaderboard/StarterCode/blob/7f124b4ddef86af887ca593b369d470bb0e3586b/train_all_multitask.py) reports an error message `ModuleNotFoundError`.

Also, [train-all-multitask-8gpu.json](https://github.com/VALUE-Leaderboard/StarterCode/blob/7f124b4ddef86af887ca593b369d470bb0e3586b/config/train-all-multitask-8gpu.json) loads data from `/data/release/txt_db_v2` and `/data/release/video_db`, but `/data` is not specified in [launch_container.sh](https://github.com/VALUE-Leaderboard/StarterCode/blob/7f124b4ddef86af887ca593b369d470bb0e3586b/launch_container.sh). 

Are `/txt/tvr_train.db` and `/data/release/txt_db_v2/tvr_train.db` same? Please explain about `_v2`.

I think [train_all_multitask.py](https://github.com/VALUE-Leaderboard/StarterCode/blob/7f124b4ddef86af887ca593b369d470bb0e3586b/train_all_multitask.py) is run on different container or environment. Could you check about running [train_all_multitask.py](https://github.com/VALUE-Leaderboard/StarterCode/blob/7f124b4ddef86af887ca593b369d470bb0e3586b/train_all_multitask.py)? Before I modify the file path on config file manually, I want to check if I missed something.

**Comment by linjieli222** [comment]
@liveseongho 

Thank you for pointing out the issue. I have fixed the configs and train_all_multitask.py. Please pull and merge the changes.

**Comment by liveseongho** [comment]
Thanks for your quick fix!
