### ISSUE TITLE
Question: Is there a way to check if the dataset is lossless?

### ISSUE THREAD

**Issue by liveseongho** [VALUE-Leaderboard/StarterCode#12]
Hi @linjieli222 

Since the dataset requires transferring large files, file corruption may occur due to network failures. Is there a way to check if the file I have received has been successfully downloaded without loss? (something like md5sum)

**Comment by linjieli222** [comment]
@liveseongho 

Thanks for your great suggestion. We can provide such information for the compressed video dbs. Will update the corresponding md5sum numbers here once available.

**Comment by linjieli222** [comment]
Sorry about the delay. Below is the md5sum results for `video_db/*.tar` files:

- `how2.tar` `f618bc183352d3eaebd2cd4be2374767`
- `tv.tar` `6fad0fa4934a6ac7fd08b3ecef66afde`
- `vatex.tar` `a75f964ae5a2a8456eb13e84eeaa5486`
- `violin.tar` `a1218a0d81ef027daaab91ee3040e66b`
- `vlep.tar` `3e43f66b6aec75279341230ba2993844`
- `yc2.tar` `c5224aa05c072ed8df9b0a7572adb13a`

**Comment by liveseongho** [comment]
Thank you!!
