### ISSUE TITLE
About the length of the sample video of the VLEP data set

### ISSUE THREAD

**Issue by RQsky** [VALUE-Leaderboard/StarterCode#15]
hello，I have noticed that the average video length of the VLEP dataset mentioned in the VALUE paper is 30s. But the article published the VLEP data set-"What is More Likely to Happen Next? Video-and-Language Future Event Prediction", in which table 2 mentioned that the Premise Event average length is 6s. why?

**Comment by linjieli222** [comment]
Here is an example data from [vlep_dev_release.jsonl](https://raw.githubusercontent.com/jayleicn/VideoLanguageFuturePred/main/data/vlep_dev_release.jsonl)
```
{"example_id": 20142, "vid_name": "friends_s03e09_seg02_clip_07_ep", "ts": [38.81, 40.37], 
 "events": ["Ross will stop, turn and point at Monica.", 
 "Ross will stop and ask Monica why she is pointing at him."], "answer": 0, "split": "dev"}
```
The average video length is the average duration of the entire video, i.e., the duration of video `friends_s03e09_seg02_clip_07_ep`. The `Premise Event` refers to the segment in the video, annotated by `"ts": [38.81, 40.37]` in the example above.

**Comment by RQsky** [comment]
So the HERO model used the entire video?

**Comment by RQsky** [comment]
So the HERO model used the entire video? And the VLEP baseline used the segment in the video?

**Comment by linjieli222** [comment]
From my understanding, both HERO and VLEP baseline uses the whole video.
