### ISSUE TITLE
How2QA Preprocessing

### ISSUE THREAD

**Issue by antoyang** [VALUE-Leaderboard/StarterCode#9]
It seems create_txtdb.sh does not process How2 data. In particular, I do not understand what is the mapping between the original YouTube video (11 character unique identifier) and the vid_name in the txtdb of How2QA (which is numerical, e.g. 29752). Do you know where I could find this information?

**Comment by linjieli222** [comment]
@antoyang Sorry about the missing information. We will be releasing the video ids mapping at our [DataRelease](https://github.com/VALUE-Leaderboard/DataRelease) repository soon.

**Comment by linjieli222** [comment]
Please check out this page for more information: https://github.com/VALUE-Leaderboard/DataRelease/tree/main/vid_mapping

**Comment by antoyang** [comment]
Thanks for this update! However there are some samples I cannot figure out, e.g. {'vid_name': 'e_1341c', 'ts': '7.20-27.90', 'qid': '6821', 'q': 'What she is gonna use?', 'a0': 'Juice.', 'a1': 'Pearl ex pigment.', 'a2': 'Water.', 'a3': 'Paint.', 'answer_idx': 1, 'input_ids': [[2264, 79, 16, 6908, 304, 116], [27324, 2463, 4], [42933, 462, 1931, 39461, 4], [25589, 4], [510, 12042, 4]], 'vid': 'e_1341c', 'target': 1} (found in val set). The video 'e_1341c' does not seem to be in the mapping.

**Comment by linjieli222** [comment]
There is a fraction of videos that we failed to map back to YouTube ids due to some information loss during the annotation process. If you wish to get the raw videos for these unmapped ones, please send your inquiry to lindsey DOT li AT microsoft DOT com.
